# -*- coding: utf-8 -*-
"""Operadores matematicos en Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_a0VdSO9lv6oULH19KULDvqphXCo3ic
"""



"""OPERADORES MATEMATICOS"""

num1 = 5
num2 = 4
res = num1 + num2
print(res)

num1 = int(input("numero 1 "))
num2 = int(input("numero 2 "))
res = num1 + num2
print("La suma de {} y {} es = {}". format(num1, num2, res))

"""**CALCULADORA**"""

num1 = int(input("numero 1 "))
num2 = int(input("numero 2 "))

suma = num1 + num2
resta = num1 - num2
multi = num1 * num2
divi = num1 / num2

print("\")

venta = float(input("¿Cuanto fue el total de la compra? "))
#Calculo del IVA
iva = venta * 0.19
#Suma del iva con la venta
Total = venta + iva
# Visualiza el total a pagar por pantalla
print("El iva es = {:,.0f} y el total a pagar es = {:,.0f}". format(iva, Total))

cal1 = float(input("Digite la calificacion1: "))
cal2 = float(input("Digite la calificacion2: "))
cal3 = float(input("Digite la calificacion3: "))

prom= round(( cal1 + cal2 + cal3 ) /3, 2)

print(f"el promedio es= {prom}")